# Generated by Django 2.1.3 on 2018-11-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181116_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iprequestlog',
            name='ip',
            field=models.CharField(max_length=50),
        ),
    ]
